### ISSUE TITLE
Screened by QA Check... it needs its on Screened Status Name..... 

### ISSUE THREAD

**Issue by jnaswhat** [krisgardner/surveyDevelopment#61]
Hi.

Me again,

For anyone now that screens at the QA Check question, can you by default label them as ScreenedQA rather than Screened? This is so that when it comes to working out the IR% it makes it easier for us rather than going into the data to figure this out, even though it tells us in Reportal, i think this should be standard.

Also in the respondent status tab, it is split so it shows you, completes, dropouts, quotafull, screened, screenedQA, error. :)

It makes things so much clearer for us and other people using reportal. :)

**Comment by krisgardner** [comment]
@jnaswhat i have updated the template so respondents get set to status of "ScreenedQA" instead of screened. You will need to export **all data** to find respondents that failed at this question / you can view via reportal , if this works for you below..i will update the template with this

![capture](https://cloud.githubusercontent.com/assets/16320935/20213811/521a0ef2-a802-11e6-8fe9-26a4b8ce3573.PNG)

**Comment by krisgardner** [comment]
Just realised i need to update the total :)

**Comment by krisgardner** [comment]
![capture](https://cloud.githubusercontent.com/assets/16320935/20213959/2077582c-a803-11e6-9831-a1816a52ff9c.PNG)

**Comment by jnaswhat** [comment]
perfect :)
